from __future__ import annotations

import re
from typing import Protocol

# Keys are generated by the application (never from user input), but validate anyway
# so a bug can't turn into path traversal on the local backend.
_VALID_KEY = re.compile(r"^[A-Za-z0-9][A-Za-z0-9/_.-]{0,500}$")


class StorageError(Exception):
    """The storage backend failed (network, permissions, disk). Retryable."""


class ObjectNotFoundError(StorageError):
    """No object exists under the key."""


def validate_key(key: str) -> str:
    if not _VALID_KEY.match(key) or ".." in key.split("/") or "//" in key:
        raise ValueError(f"Invalid storage key: {key!r}")
    return key


class ObjectStorage(Protocol):
    """Minimal async blob store. Implementations must be safe to share across requests."""

    async def put(self, key: str, data: bytes, *, content_type: str) -> None: ...

    async def get(self, key: str) -> bytes: ...

    async def delete(self, key: str) -> None:
        """Remove the object. Deleting a missing object is not an error."""
        ...
